name: Docker Image CI

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  pull_request:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name
      - name: setup mongo
        run: docker run -w /workspaces/videos_backend/ my-image-name ./setup.sh
      - name: run flask
        run: docker run -w /workspaces/videos_backend/ my-image-name python -m app test.env
      - name: run test
        run: docker run -w /workspaces/videos_backend/ my-image-name python .vs_code/run_nose.py /workspaces/videos_backend/tests/api_test.py -v -s
