name: Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: '6.2.6'
        
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Start mariadb
      uses: getong/mariadb-action@v1.1
      
    - name: Create Mysql Databases
      run: |
        sudo systemctl start mysql.service
        chmod 777 ./setup_mysql.sh
        sh ./setup_mysql.sh

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run API Tests
      run: |
        python app.py test.env &
        sleep 5
        python tests/run_tests.py
