name: Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
        - '8888:3306'
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: videos_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: '6.2.6'
      
    - name: Create Mysql Databases
      run: |
        sudo systemctl start mysql.service
        mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXIST videos_test; CREATE USER userapp@localhost identified by '1234';  GRANT ALL privileges ON *.* TO userapp@localhost;'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run API Tests
      run: |
        python app.py test.env &
        sleep 5
        python tests/run_tests.py
