name: Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: '6.2.6'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '4.4'
    - name: Create Mongo Databases
      run: mongo < setup_local_db.js
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run API Tests
      run: |
        python app.py test.env &
        sleep 5
        python tests/run_tests.py
